// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDETL9h5f51-B5gyw7kR35udiWcfFPE1ZM',
    appId: '1:425446096728:web:c296954aeb453e124c6f2d',
    messagingSenderId: '425446096728',
    projectId: 'my-cool-project-445c4',
    authDomain: 'my-cool-project-445c4.firebaseapp.com',
    storageBucket: 'my-cool-project-445c4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF16tolNdXB9hBmdnhojcNyJYNkAKMrUw',
    appId: '1:425446096728:android:12248347d97077934c6f2d',
    messagingSenderId: '425446096728',
    projectId: 'my-cool-project-445c4',
    storageBucket: 'my-cool-project-445c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnlHglq7VQEFflYe2qadRbf2l9RwJAmoQ',
    appId: '1:425446096728:ios:715eb8fbe52bea764c6f2d',
    messagingSenderId: '425446096728',
    projectId: 'my-cool-project-445c4',
    storageBucket: 'my-cool-project-445c4.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesAppTry2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnlHglq7VQEFflYe2qadRbf2l9RwJAmoQ',
    appId: '1:425446096728:ios:715eb8fbe52bea764c6f2d',
    messagingSenderId: '425446096728',
    projectId: 'my-cool-project-445c4',
    storageBucket: 'my-cool-project-445c4.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesAppTry2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDETL9h5f51-B5gyw7kR35udiWcfFPE1ZM',
    appId: '1:425446096728:web:08ac9c2fdf8236db4c6f2d',
    messagingSenderId: '425446096728',
    projectId: 'my-cool-project-445c4',
    authDomain: 'my-cool-project-445c4.firebaseapp.com',
    storageBucket: 'my-cool-project-445c4.firebasestorage.app',
  );
}
